openapi: 3.0.0
info:
  title: AXA
  description: Rest API for AXA
  version: 0.1.9

components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer

paths:
  /api/login:
    post:
      summary: Returns a bearer token.
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              parameters:
              required:
                - client_id
                - client_secret
              properties:
                client_id:
                  type: string
                client_secret:
                  type: string
      responses:
        "200": # status code
          description: Returns a bearer token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  type:
                    type: string
        "401": # status code
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /api/clients:
    get:
      summary: Returns a list of clients.
      tags:
        - clients
      security:
        - bearerAuth: []
      responses:
        "200": # status code
          description: A JSON array of clients
          content:
            application/json:
              type: object
              schema:
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
                  role:
                    type: string
        "304": # status code
          description: A JSON array of clients
          content:
            application/json:
              type: object
        "401": # status code
          content:
            application/json:
              type: object
              schema:
                properties:
                  message:
                    type: string

  /api/policies:
    get:
      summary: Returns a list of policies.
      security:
        - bearerAuth: []
      tags:
        - policies
      responses:
        "200": # status code
          description: A JSON array of policies
          content:
            application/json:
              type: object
              schema:
                properties:
                  id:
                    type: string
                  amountInsured:
                    type: string
                  email:
                    type: string
                  inceptionDate:
                    type: string
                  installmentPayment:
                    type: string
                  clientId:
                    type: string
        "304": # status code
          content:
            application/json:
              type: object
        "401": # status code
          content:
            application/json:
              type: object
              schema:
                properties:
                  message:
                    type: string
